### ISSUE TITLE
수정 모드에 진입했을 때 setEditing(_: animation:)을 활용해보는건 어떨까요?

### ISSUE THREAD

**Issue by blooper20** [ILGOB/It-sME#111]
# 제안 사항
> 어떤 제안 인지
수정 모드를 진입했을 때 `setEditing(_: animation:)` 함수를 활용하여 테이블 수정을 더욱 간편하게 하자
# 근거
> 왜 이런 제안을 생각 하게 되었는 지
테이블을 생성하고 난 뒤에 테이블 스타일을 .insetGroued으로 변경하려는 방법을 찾다가 setEditing함수를 찾게되었고 제가 생각했던 기능들이 쉽게 구현되어있어서 생각하게 되었다.
# 참고 자료
> [간단하게 설명과 gif로 되어있는 자료가 보기 편한 사이트](https://furang-note.tistory.com/11)
> [애플공식문서](https://developer.apple.com/documentation/uikit/uitableview/1614876-setediting)
> ![image](https://user-images.githubusercontent.com/70786167/220834830-c0c02d92-6b17-4d49-a31e-3e355490f46a.png)

**Comment by woin2ee** [comment]
구현이 간편할지는 모르겠지만 UI 적으로 좋은것같습니다.
