### ISSUE TITLE
PeriodInputCell을 공통 컴포넌트로 사용하는건 어떨까요?

### ISSUE THREAD

**Issue by blooper20** [ILGOB/It-sME#131]
# 제안 사항
> PeriodInputCell과 관련 기능들을 공통 컴포넌트로 사용하여 학력 수정 화면 뿐만 아니라 카테고리 추가/수정 화면에서도 사용할 수 있게 하는건 어떨까요??
# 근거
> 공통적인 기능이 너무 많음
- titleLabel은 .init(title: String) 으로 해결되는걸 확인해봄
- 졸업여부 -> 완료여부, 졸업 -> 완료, 재학중 -> 진행중 이런 방식으로 변경할 수 있다면 나머지 기능은 동일하다고 생각함

**Comment by woin2ee** [comment]
관련 Cell 을 최대한 일반화해서 필요한 곳에 사용할 수 있게끔 업데이트하겠습니다.
