### ISSUE TITLE
프로젝트 마무리 까지 남은 작업

### ISSUE THREAD

**Issue by blooper20** [ILGOB/It-sME#133]
### @blooper20
- 공통
    - [x] #137
    - [x] #138
    - [ ] #139

-  카테고리 편집
    - [x] 공통
    - [x] 기간 정하는 테이블 #131 관련
-  카테고리 추가
    - [x] 공통
    - [x] #135

- 자기소개서 편집
    - [x] 공통

- 자기소개서 추가
    - [x] 공통
    - [x] #136

- TotalCV편집
    - [x] 수정 완료 버튼을 눌렀을 때 변경된 사항에 대한 데이터 처리
___
### @woin2ee
- [ ] 해야할 사항

___

# 남은 해야할 사항
### 화면 구현
- [ ] #140
- [ ] #141

### 파이어베이스 DB
- [ ] 첫 로그인 시 계정 생성 (회원가입 화면)
- [ ] 데이터 업데이트 & 추가 & 삭제 API 구현

**Comment by woin2ee** [comment]
Closed due to Jira Software use.
