### ISSUE TITLE
🛠️버그 발생⚙️

### ISSUE THREAD

**Issue by blooper20** [ILGOB/It-sME#47]
# When
> 어떨 때 발생 하는 지
- 홈 화면이 생길 때
<img width="385" alt="스크린샷 2022-12-17 오후 5 38 22" src="https://user-images.githubusercontent.com/70786167/208233559-d8862533-ec64-41a8-b6ee-a8eece9fb039.png">

# Where
> 어떤 파일에서 발생한 건 지
- HomeViewController.swift
# What 
> 어떤 것을 수정 하고 싶은 지
- 스크롤뷰가 제자리로 원상 복귀
> 제가 생각하기엔 스크롤 뷰의 스냅킷이 유저정보 컴포넌트의 밑으로 잡혀있어 유저정보가 사라지면서 갈 길을 잃어버린...
## 해결해야 하는 리스트
- [x] 스크롤 뷰의 원상 복귀
> 생각한 해결 방법
- 빈 껍데기의 유저정보 컴포넌트를 생성한다?
- 스크롤 뷰 오토레이아웃을 컴포넌트의 밑이 아닌 뷰 전체의 아래쪽에서 부터 잡도록 한다?

**Comment by woin2ee** [comment]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/81426024/208336529-045cff7c-7e0e-46f2-8dfe-b293532a7844.png">
이부분은 어차피 4개 고정으로 잡혀있으므로 스켈레톤 뷰 형식으로 빈 껍데기의 컴포넌트를 4개 생성해서, 유저정보를 가져오는 중이더라도 레이아웃이 깨지지 않도록 하는게 좋아보입니당
