### ISSUE TITLE
Then 라이브러리 사용

### ISSUE THREAD

**Issue by woin2ee** [ILGOB/It-sME#51]
# 제안 사항
> 어떤 제안 인지

현재 프로젝트에 Then 라이브러리 적용
# 근거
> 왜 이런 제안을 생각 하게 되었는 지

코드로 UI 를 구성하는데 필요한 보일러플레이트 코드를 좀 더 가독성이 좋게 바꿔줄 수 있다고 생각
# 참고 자료

https://github.com/devxoul/Then

**Comment by blooper20** [comment]
링크의 자료를 봤는데 확실히 보기도 작성하기도 편해보여 적용하면 좋을 것 같습니다.

한 가지 이해가 안되는 부분은 `then(), with()`는 이해가 됐는데 
`do()` 를 어떤 식으로 사용하는 지 감이 안잡히는 것 같습니다.

**Comment by woin2ee** [comment]
`then()` 만 보고 나머지는 제대로 안봤었는데 다시 확인해보니 
`do()` 는 반환값이 없기때문에 해당 객체로 부터 무언가를 수행하고 끝내고 싶을때 사용하는것 같습니다.
RxSwift 의 `do()` 랑 비슷한 느낌?

**Comment by woin2ee** [comment]
Then 적용 완료
